# Generated by Django 2.2.13 on 2020-10-07 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 7, 5, 27, 951434, tzinfo=utc)),
        ),
    ]
