# Generated by Django 2.2.13 on 2020-10-07 08:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20201007_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 8, 56, 3, 40126, tzinfo=utc)),
        ),
    ]
