# Generated by Django 2.2.13 on 2020-10-07 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_auto_20201007_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
