# Generated by Django 2.2.13 on 2020-09-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
