# Generated by Django 2.2.13 on 2020-09-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.TextField(blank=True, max_length=15),
        ),
    ]
