# Generated by Django 2.2.13 on 2020-09-23 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_profile_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loggedIn', models.BooleanField(default=True)),
                ('token', models.TextField()),
                ('loginTime', models.DateTimeField()),
                ('logoutTime', models.DateTimeField(blank=True, null=True)),
                ('device', models.TextField(blank=True, null=True)),
                ('ip', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
