# Generated by Django 2.2.13 on 2020-09-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_loginhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='location',
        ),
    ]
