# Generated by Django 2.2.13 on 2020-09-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_loginhistory_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastSeen',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='privateComments',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ratingView',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
