# Generated by Django 2.2.13 on 2020-09-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200923_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(max_length=255)),
                ('otp', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
