# Generated by Django 2.2.13 on 2020-09-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tempusertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempusertoken',
            name='email',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tempusertoken',
            name='isMobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempusertoken',
            name='mobile',
            field=models.TextField(blank=True, max_length=15),
        ),
    ]
