# Generated by Django 2.2.13 on 2020-09-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200927_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempusertoken',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
