# Generated by Django 2.2.13 on 2020-09-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_tempusertoken_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
