# Generated by Django 2.2.13 on 2020-10-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200928_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fans',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mopics',
        ),
    ]
