# Generated by Django 2.2.13 on 2020-10-07 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201004_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 7, 5, 27, 948442, tzinfo=utc)),
        ),
    ]
