# Generated by Django 2.2.13 on 2020-10-07 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_follow_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='giphy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 8, 55, 51, 235715, tzinfo=utc)),
        ),
    ]
