# Generated by Django 2.2.13 on 2020-10-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20201007_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fcm',
            field=models.TextField(blank=True, null=True),
        ),
    ]
