# Generated by Django 2.2.13 on 2020-11-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_profile_fcm'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpAnon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('token', models.TextField()),
                ('otp', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
