# Generated by Django 2.2.13 on 2020-11-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_userotp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
    ]
