# Generated by Django 2.2.13 on 2020-09-30 07:17

from django.db import migrations, models
import messenger.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messenger',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=messenger.models.PathAndRename('')),
        ),
    ]
