# Generated by Django 2.2.13 on 2020-10-04 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20200930_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='messenger',
            name='messageReply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.Messenger'),
        ),
    ]
