# Generated by Django 2.2.13 on 2020-10-05 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
        ('messenger', '0004_messenger_messagereply'),
    ]

    operations = [
        migrations.AddField(
            model_name='messenger',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='story.Story'),
        ),
    ]
