# Generated by Django 2.2.13 on 2020-10-07 06:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_messenger_mopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messenger',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 6, 59, 53, 748104, tzinfo=utc)),
        ),
    ]
