# Generated by Django 2.2.13 on 2020-10-07 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_auto_20201007_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messenger',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 7, 5, 27, 952431, tzinfo=utc)),
        ),
    ]
