# Generated by Django 2.2.13 on 2020-10-07 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_auto_20201007_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='messenger',
            name='gif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messenger',
            name='sticker',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messenger',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 12, 11, 52, 775345, tzinfo=utc)),
        ),
    ]
