# Generated by Django 2.2.13 on 2020-10-29 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import messenger.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0014_inboxtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True)),
                ('name', models.TextField()),
                ('bg', models.TextField()),
                ('bgDark', models.TextField()),
                ('bgLight', models.TextField()),
                ('color', models.TextField()),
                ('hint', models.TextField()),
                ('gradient', models.TextField()),
                ('secondary', models.TextField()),
                ('primary', models.TextField()),
                ('secondaryAccent', models.TextField()),
                ('primaryAccent', models.TextField()),
                ('secondaryAccentHint', models.TextField()),
                ('primaryAccentHint', models.TextField()),
                ('preview', models.ImageField(blank=True, null=True, upload_to=messenger.models.PathAndRename(''))),
                ('background', models.ImageField(blank=True, null=True, upload_to=messenger.models.PathAndRename(''))),
                ('header', models.ImageField(blank=True, null=True, upload_to=messenger.models.PathAndRename(''))),
                ('footer', models.ImageField(blank=True, null=True, upload_to=messenger.models.PathAndRename(''))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
