# Generated by Django 2.2.13 on 2020-10-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0015_messengertheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengertheme',
            name='bg',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='messengertheme',
            name='bgDark',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='messengertheme',
            name='bgLight',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='messengertheme',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='messengertheme',
            name='gradient',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='messengertheme',
            name='hint',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='messengertheme',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='messengertheme',
            name='primary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='messengertheme',
            name='primaryAccent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='messengertheme',
            name='primaryAccentHint',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='messengertheme',
            name='secondary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='messengertheme',
            name='secondaryAccent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='messengertheme',
            name='secondaryAccentHint',
            field=models.CharField(max_length=100),
        ),
    ]
