# Generated by Django 2.2.13 on 2020-10-29 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0016_auto_20201029_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.MessengerTheme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_user', to=settings.AUTH_USER_MODEL)),
                ('user_secondary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_user_sec', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
