# Generated by Django 2.2.13 on 2020-10-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0018_messengertheme_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='themedata',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
