import React from "react";
import { StyleSheet } from "react-native";
import * as Constants from "../Constants";

export const ThemeMap = {
  default: {
    id: "default",
    name: "Default Theme",
    bg: { backgroundColor: "#ffffff" },
    bgDark: { backgroundColor: "#e9e9e9" },
    bgLight: { backgroundColor: "#ffffff" },
    color: { color: "#000", tintColor: "#000" },
    hint: { color: "#8f9bb3" },
    image: null,
    footerImage: null,
    headerImage: null,
    gradient: ["rgba(0,0,255,0.07)", "rgba(255,0,0,0.05)"],
    secondary: "#d5d5d5",
    primary: "#7f7fff",
    secondaryAccent: "#000",
    primaryAccent: "#000",
    secondaryAccentHint: "#e9e9e9",
    primaryAccentHint: "#e9e9e9",
  },
  festival: {
    id: "festival",
    name: "Festival Theme",
    preview: Constants.MEDIA_URL + "images/halloween.png",
    bg: { backgroundColor: "#FF8B0F" },
    bgDark: { backgroundColor: "#c26400" },
    bgLight: { backgroundColor: "#ffaa50" },
    color: { color: "#000", tintColor: "#000" },
    hint: { color: "#444" },
    image: Constants.MEDIA_URL + "images/halloween_background.png",
    footerImage: null,
    headerImage: null,
    gradient: ["#cba883", "rgba(70,42,11,0.4)"],
    secondary: "#d9d9d9",
    primary: "#ffaa50",
    secondaryAccent: "#000",
    primaryAccent: "#000",
    secondaryAccentHint: "#e9e9e9",
    primaryAccentHint: "#e9e9e9",
  },
  seasonal: {
    id: "seasonal",
    name: "Seasonal Theme",
    preview: Constants.MEDIA_URL + "images/winter.png",
    bg: { backgroundColor: "#bedce6" },
    bgDark: { backgroundColor: "#7f7fff" },
    bgLight: { backgroundColor: "#bed5dd" },
    color: { color: "#000", tintColor: "#000" },
    hint: { color: "#8f9bb3" },
    image: Constants.MEDIA_URL + "images/winter_background.png",
    footerImage: Constants.MEDIA_URL + "images/winter_footer.png",
    headerImage: Constants.MEDIA_URL + "images/winterheader.png",
    gradient: ["#96d1e5", "#bed5dd"],
    secondary: "#bedce6",
    primary: "#7f7fff",
    secondaryAccent: "#000",
    primaryAccent: "#000",
    secondaryAccentHint: "#e9e9e9",
    primaryAccentHint: "#e9e9e9",
  },
};
const MessengerTheme = {
  dark: {
    id: "default",
    name: "Default Theme",
    bg: { backgroundColor: "#111111" },
    bgDark: { backgroundColor: "#ffffff" },
    bgLight: { backgroundColor: "#333333" },
    color: { color: "#e9e9e9", tintColor: "#e9e9e9" },
    hint: { color: "rgba(255,255,255,0.5)" },
    image: null,
    footerImage: null,
    headerImage: null,
    gradient: ["#000", "#111"],
    secondary: "#222",
    primary: "#666",
    secondaryAccent: "#fff",
    primaryAccent: "#fff",
    secondaryAccentHint: "#e9e9e9",
    primaryAccentHint: "#e9e9e9",
  },
  light: {
    id: "default",
    name: "Default Theme",
    bg: { backgroundColor: "#ffffff" },
    bgDark: { backgroundColor: "#333" },
    bgLight: { backgroundColor: "#ffffff" },
    color: { color: "#000", tintColor: "#000" },
    hint: { color: "#8f9bb3" },
    image: null,
    footerImage: null,
    headerImage: null,
    gradient: ["rgba(0,0,255,0.07)", "rgba(255,0,0,0.05)"],
    secondary: "#d5d5d5",
    primary: "#7f7fff",
    secondaryAccent: "#000",
    primaryAccent: "#000",
    secondaryAccentHint: "#e9e9e9",
    primaryAccentHint: "#e9e9e9",
  },
};
export default MessengerTheme;
