# Generated by Django 2.2.13 on 2020-09-16 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mopic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(max_length=255)),
                ('location', models.TextField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MopicTagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mopic.Mopic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MopicRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('mopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mopic.Mopic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MopicMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to=mopic.models.PathAndRename(''))),
                ('mopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mopic.Mopic')),
            ],
        ),
        migrations.CreateModel(
            name='MopicLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('mopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mopic.Mopic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MopicCommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MopicComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=255)),
                ('private', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('mopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mopic.Mopic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mopic.Mopic')),
            ],
        ),
    ]
