# Generated by Django 2.2.13 on 2020-09-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mopic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mopic',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mopic',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mopic',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
