# Generated by Django 2.2.13 on 2020-09-16 12:34

from django.db import migrations, models
import mopic.models


class Migration(migrations.Migration):

    dependencies = [
        ('mopic', '0002_auto_20200916_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='mopicmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=mopic.models.PathAndRename('')),
        ),
    ]
