# Generated by Django 2.2.13 on 2020-09-17 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mopic', '0003_mopicmedia_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mopiccommentreply',
            name='commentMain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mopic.MopicComment'),
        ),
    ]
