# Generated by Django 2.2.13 on 2020-10-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mopic', '0005_auto_20200917_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mopic',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='mopic',
            name='rate',
        ),
        migrations.AlterField(
            model_name='mopic',
            name='comments',
            field=models.BooleanField(default=True),
        ),
    ]
