# Generated by Django 2.2.13 on 2020-10-07 06:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mopic', '0006_auto_20201007_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='mopic',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mopic',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 6, 42, 4, 52635, tzinfo=utc)),
        ),
    ]
