# Generated by Django 2.2.13 on 2020-10-07 06:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mopic', '0007_auto_20201007_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mopic',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 6, 59, 53, 741122, tzinfo=utc)),
        ),
    ]
