# Generated by Django 2.2.13 on 2020-10-07 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mopic', '0008_auto_20201007_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mopic',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 7, 5, 27, 944452, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mopiccomment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 7, 5, 27, 946447, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mopiccommentreply',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 7, 5, 27, 946447, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mopiclike',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 7, 5, 27, 945450, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mopicrate',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 7, 5, 27, 946447, tzinfo=utc)),
        ),
    ]
