# Generated by Django 2.2.13 on 2020-10-07 08:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mopic', '0010_auto_20201007_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mopic',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 8, 56, 3, 33145, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mopiccomment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 8, 56, 3, 35140, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mopiccommentreply',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 8, 56, 3, 35140, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mopiclike',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 8, 56, 3, 34142, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mopicrate',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 8, 56, 3, 34142, tzinfo=utc)),
        ),
    ]
