# Generated by Django 2.2.13 on 2020-10-07 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mopic', '0013_auto_20201007_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mopic',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mopiccomment',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mopiccommentreply',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mopiclike',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mopicrate',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
