# Generated by Django 2.2.13 on 2020-10-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mopic', '0014_auto_20201007_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='tag',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='mopictagged',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
